Vagrant.configure("2") do |config|
    cpus = 1
    memory = 1024

    server = {
        "name": "lmoheymaS",
        "ip": "192.168.56.110"
    }

    config.vm.box = "hashicorp-education/ubuntu-24-04"
    config.vm.box_version = "0.1.0"

    config.vm.define server[:name] do |machine|
        machine.vm.hostname = server[:name]
        machine.vm.network "private_network", ip: server[:ip]
        machine.vm.provider "virtualbox" do |vb|
            vb.customize ["modifyvm", :id, "--name", server[:name]]
            vb.memory = memory
            vb.cpus = cpus
        end

        config.vm.provision :docker
        machine.vm.provision "shell", path: "k3s_server_install.sh"
        machine.vm.provision "shell", path: "deploy_apps.sh"
    end
end
