apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-app
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-app
  template:
    metadata:
      labels:
        app: simple-app
    spec:
      hostNetwork: true
      containers:
      - name: simple-app-container
        image: wil42/playground:v1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8888

apiVersion: v1
kind: Service
metadata:
  name: simple-app
  namespace: dev
spec:
  selector:
    app: simple-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8888